# Профиль prod — настраивается при деплое на сервер
# Укажи SPRING_PROFILES_ACTIVE=prod и переменные:
# DATABASE_URL, DATABASE_USER, DATABASE_PASSWORD
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    liquibase-schema: public
    default-schema: englishmovies
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Telegram (пока те же значения, что и на dev; потом перейти на переменные окружения)
telegram:
  bot-token: 8217894172:AAEq0W2pRxfw-qjdCaj1nKgLOdfCgOvTkgg
  chat-id: "-1002329783519"
